### ISSUE TITLE
Bounding box is sometimes mirrored or collapses

### ISSUE THREAD

**Issue by undecaf** [lekoala/barcode-detector-zbar#2]
Depending on the tilt of the barcode, the bounding box sometimes appears mirrored at an edge of the barcode (as in the attached image), or it collapses to a single line.

![screenshot_2021-11-27_16-13-00](https://user-images.githubusercontent.com/7375196/143687000-d7e81e7a-7a65-4624-b50f-9c8b306762ce.png)

**Comment by lekoala** [comment]
@undecaf is it fixed with your PR? (just published 1.0.2)

**Comment by undecaf** [comment]
@lekoala Yes it is, I tested it before I made the PR

**Comment by lekoala** [comment]
good to know! closing the issue
