### ISSUE TITLE
include esbuild in devDependencies

### ISSUE THREAD

**Issue by zinglax** [lekoala/barcode-detector-zbar#4]
For building this module, esbuild is required but not included in the packages.json

Adding a section like the following might help.
```js
  "devDependencies": {
    "esbuild": "^0.14.11"
  },
```

_Hey! just wanted to let you know too that I love your zbar.wasm > BarcodeDetector API polyfill, super powerful.  I am new/inexperenced within the JS world but would love to use this lib and help make it better.  I haven't ever done a PR on github before but don't mind creating one to do this, LMK!_

**Comment by lekoala** [comment]
Hey ! Thanks for your interest. While I know everyone include build tools, I tend not to do it and install my build tools globally. It feels like a waste to install esbuild for every single project. Maybe I'm a rebel :) so far it doesn't bring any benefit to include it. Is it an issue to install it globally ?

**Comment by zinglax** [comment]
That is not a problem at all! Just was trying to build and hit that error that it was missing and thats like the one thing I know how to do with a node project. Good work with this lib though, I will keep an eye out if I see anything else and let you know! Thanks for the response!
