### ISSUE TITLE
RuntimeError: Aborted(CompileError: WebAssembly.instantiate()

### ISSUE THREAD

**Issue by preflower** [lekoala/barcode-detector-zbar#5]
when i use it in my project, it return

Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.

**Comment by preflower** [comment]
this is my import code
```
import BarcodeDetectorPolyfill from 'barcode-detector-zbar/BarcodeDetectorPolyfill.min.js'

BarcodeDetectorPolyfill.setupPolyfill()
```

**Comment by lekoala** [comment]
probably more of an issue with zbar.wasm

**Comment by preflower** [comment]
The reason is that it is failed to get a WASM file, i try to put into my static folder and then it's working
