### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by dylanvdmerwe** [lekoala/barcode-detector-zbar#7]
When trying to use this in an Angular project, I get an exception in the browser:
`SyntaxError: Unexpected token 'export'`

Any idea what could be causing this?

![image](https://user-images.githubusercontent.com/2852839/165311254-78388b8e-9495-4dbb-9691-e918a0bfc756.png)

**Comment by lekoala** [comment]
this is regular es6 export, not sure about how it is used in angular
